name:  Update Mozilla cert.pem Nightly

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Update Mozilla cert.pem Nightly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up commit signing
        uses: Chia-Network/actions/commit-sign/gpg@main
        with:
          gpg_private_key: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_KEY }}
          passphrase: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_PASSPHRASE }}

      - name: Update Mozilla cert.pem Nightly
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          curl --cacert cacert.pem --remote-name https://curl.se/ca/cacert.pem
          git status
          DATE="$(date)"
          export DATE
          ( git commit cacert.pem -m "cacert.pem updated $DATE" && git push origin main ) || true
          git status

      - name: Hook Blockchain CA Update workflow
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.WORKFLOW_TRIGGERS }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/Chia-Network/chia-blockchain/actions/workflows/mozilla-ca-cert.yml/dispatches --data '{"ref": "main" }'
